spring.application.name=demo
# for https
server.forward-headers-strategy=framework 
spring.datasource.url=jdbc:mysql://localhost:3306/loomlearn
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
